export tag=prod-{{.Date}}-1
export GOPROXY=https://goproxy.cn,direct
build:
	echo "building {{.App}} mirror"
	docker build -f DockerFile -t {{.Image}}:${tag} .

push_image: build
	echo "pushing {{.App}} mirror"
	docker push {{.Image}}:${tag}