# first execute: kubectl apply -f https://github.com/jetstack/cert-manager/releases/latest/download/cert-manager.yaml
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: lets-encrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: your-email@example.com
    privateKeySecretRef:
      name: lets-encrypt-prod
    solvers:
      - http01:
          ingress:
            class: istio
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: admin-cert
spec:
  secretName: admin-cert
  dnsNames:
    - example.com
  issuerRef:
    name: lets-encrypt-prod
    kind: Issuer
